// Datos globales
export const userData = {
  nombre: "Juan",
  apellido: "Pérez",
  email: "juan.perez@email.com",
  telefono: "+54 11 1234-5678",
  documento: "12345678",
  ubicacion: "Buenos Aires, Argentina",
  fechaRegistro: "2024-01-01",
  avatar: null,
};

export const coursesData = {
  1: {
    id: "1",
    nombre: "Introducción a la Programación",
    progreso: 75,
    estadoCuota: "al_dia",
    completado: false,
    certificadoDisponible: false,
    estado: "activo",
    fechaInicio: "2024-01-15",
    fechaFin: "2024-04-15",
    leccionesCompletadas: 18,
    totalLecciones: 24,
    horasEstudio: 45,
    promedio: 87,
    montoMatricula: "$299",
    fechaVencimiento: "2024-02-15",
    instructor: "Prof. María García",
    descripcion: "Aprende los fundamentos de la programación con Python",
  },
  2: {
    id: "2",
    nombre: "Desarrollo Web Avanzado",
    progreso: 100,
    estadoCuota: "al_dia",
    completado: true,
    certificadoDisponible: true,
    estado: "completado",
    fechaInicio: "2023-09-01",
    fechaFin: "2023-12-15",
    leccionesCompletadas: 32,
    totalLecciones: 32,
    horasEstudio: 120,
    promedio: 94,
    montoMatricula: "$499",
    fechaVencimiento: "Pagado",
    instructor: "Prof. Carlos Rodríguez",
    descripcion: "Domina React, Node.js y tecnologías web modernas",
  },
  3: {
    id: "3",
    nombre: "Diseño Gráfico Digital",
    progreso: 45,
    estadoCuota: "pendiente",
    completado: false,
    certificadoDisponible: false,
    estado: "activo",
    fechaInicio: "2024-02-01",
    fechaFin: "2024-05-30",
    leccionesCompletadas: 9,
    totalLecciones: 20,
    horasEstudio: 28,
    promedio: 78,
    montoMatricula: "$399",
    fechaVencimiento: "2024-02-28",
    instructor: "Prof. Ana López",
    descripcion: "Crea diseños impactantes con Adobe Creative Suite",
  },
  4: {
    id: "4",
    nombre: "Marketing Digital",
    progreso: 20,
    estadoCuota: "vencida",
    completado: false,
    certificadoDisponible: false,
    estado: "suspendido",
    fechaInicio: "2024-01-10",
    fechaFin: "2024-04-10",
    leccionesCompletadas: 3,
    totalLecciones: 15,
    horasEstudio: 12,
    promedio: 65,
    montoMatricula: "$349",
    fechaVencimiento: "2024-02-10",
    instructor: "Prof. Luis Martínez",
    descripcion: "Estrategias efectivas de marketing en redes sociales",
  },
};

export const paymentsData = [
  {
    id: 1,
    curso: "Desarrollo Web Avanzado",
    monto: "$499",
    fecha: "2023-09-01",
    estado: "pagado",
    metodo: "Tarjeta de Crédito",
  },
  {
    id: 2,
    curso: "Introducción a la Programación",
    monto: "$299",
    fecha: "2024-01-15",
    estado: "pagado",
    metodo: "Transferencia Bancaria",
  },
  {
    id: 3,
    curso: "Diseño Gráfico Digital",
    monto: "$399",
    fecha: "2024-02-01",
    estado: "pendiente",
    metodo: "Pendiente",
  },
  {
    id: 4,
    curso: "Marketing Digital",
    monto: "$349",
    fecha: "2024-01-10",
    estado: "vencido",
    metodo: "No pagado",
  },
];